export const PROJECT_TYPES = [
  { value: "commission", label: "Commission" },
  { value: "collaboration", label: "Collaboration" },
  { value: "technical", label: "Technical / R&D" },
  { value: "consultation", label: "Consultation" },
  { value: "workshop", label: "Workshop / Teaching" },
  { value: "live-performance", label: "Live Performance / Show" },
  { value: "tour", label: "Tour (Multiple Dates)" },
  { value: "installation-temp", label: "Temporary Installation" },
  { value: "installation-perm", label: "Permanent Installation" },
] as const;

export const CLIENT_TYPES = [
  { value: "global-brand", label: "Global Brand" },
  { value: "big-brand", label: "Big Brand (National)" },
  { value: "small-brand", label: "Small Brand / Startup" },
  { value: "institution", label: "Institution / Museum" },
  { value: "festival", label: "Festival" },
  { value: "club-venue", label: "Club / Live Venue" },
  { value: "club-venue", label: "Theater" },
  { value: "musician", label: "Musician / Artist" },
  { value: "exhibition", label: "Exhibition" },
  { value: "agency", label: "Agency" },
  { value: "private", label: "Private Client" },
  { value: "other", label: "Other" },
] as const;

export const PROJECT_LENGTHS = [
  { value: "day", label: "Single day" },
  { value: "2-5-days", label: "2–5 days" },
  { value: "1-2-weeks", label: "1–2 weeks" },
  { value: "1-3-months", label: "1–3 months" },
  { value: "3-6-months", label: "3–6 months" },
  { value: "6plus-months", label: "6+ months" },
] as const;

export const CONTRACTED_AS = [
  { value: "freelancer", label: "Freelancer / individual" },
  { value: "studio", label: "Studio / company" },
] as const;

export const RATE_REPRESENTATIVENESS = [
  { value: "standard", label: "Standard — my typical rate" },
  { value: "below_market", label: "Below market — discounted (passion / friend / portfolio)" },
  { value: "above_market", label: "Above market — premium (rush / prestige / difficult)" },
] as const;

export const RATE_TYPES = [
  { value: "project", label: "Project fee (flat rate)" },
  { value: "daily", label: "Day rate" },
  { value: "hourly", label: "Hourly rate" },
  { value: "retainer", label: "Monthly retainer" },
] as const;

export const YOUR_ROLES = [
  { value: "solo", label: "Solo (full project)" },
  { value: "lead", label: "Lead creative" },
  { value: "key-contributor", label: "Key contributor" },
  { value: "subcontractor", label: "Subcontractor / hired in" },
] as const;

export const CURRENCY_OPTIONS = [
  { value: "USD", label: "USD — US Dollar" },
  { value: "EUR", label: "EUR — Euro" },
  { value: "GBP", label: "GBP — British Pound" },
  { value: "CHF", label: "CHF — Swiss Franc" },
  { value: "JPY", label: "JPY — Japanese Yen" },
  { value: "CAD", label: "CAD — Canadian Dollar" },
  { value: "AUD", label: "AUD — Australian Dollar" },
  { value: "NZD", label: "NZD — New Zealand Dollar" },
  { value: "HKD", label: "HKD — Hong Kong Dollar" },
  { value: "SGD", label: "SGD — Singapore Dollar" },
  { value: "NOK", label: "NOK — Norwegian Krone" },
  { value: "SEK", label: "SEK — Swedish Krona" },
  { value: "DKK", label: "DKK — Danish Krone" },
  { value: "HUF", label: "HUF — Hungarian Forint" },
  { value: "CZK", label: "CZK — Czech Koruna" },
  { value: "PLN", label: "PLN — Polish Zloty" },
  { value: "RON", label: "RON — Romanian Leu" },
  { value: "BGN", label: "BGN — Bulgarian Lev" },
  { value: "HRK", label: "HRK — Croatian Kuna" },
  { value: "RSD", label: "RSD — Serbian Dinar" },
  { value: "UAH", label: "UAH — Ukrainian Hryvnia" },
  { value: "GEL", label: "GEL — Georgian Lari" },
  { value: "TRY", label: "TRY — Turkish Lira" },
  { value: "RUB", label: "RUB — Russian Ruble" },
  { value: "KZT", label: "KZT — Kazakhstani Tenge" },
  { value: "AZN", label: "AZN — Azerbaijani Manat" },
  { value: "AMD", label: "AMD — Armenian Dram" },
  { value: "ILS", label: "ILS — Israeli Shekel" },
  { value: "AED", label: "AED — UAE Dirham" },
  { value: "SAR", label: "SAR — Saudi Riyal" },
  { value: "QAR", label: "QAR — Qatari Riyal" },
  { value: "KWD", label: "KWD — Kuwaiti Dinar" },
  { value: "BHD", label: "BHD — Bahraini Dinar" },
  { value: "EGP", label: "EGP — Egyptian Pound" },
  { value: "MAD", label: "MAD — Moroccan Dirham" },
  { value: "TND", label: "TND — Tunisian Dinar" },
  { value: "DZD", label: "DZD — Algerian Dinar" },
  { value: "ZAR", label: "ZAR — South African Rand" },
  { value: "NGN", label: "NGN — Nigerian Naira" },
  { value: "KES", label: "KES — Kenyan Shilling" },
  { value: "GHS", label: "GHS — Ghanaian Cedi" },
  { value: "ETB", label: "ETB — Ethiopian Birr" },
  { value: "TZS", label: "TZS — Tanzanian Shilling" },
  { value: "INR", label: "INR — Indian Rupee" },
  { value: "PKR", label: "PKR — Pakistani Rupee" },
  { value: "BDT", label: "BDT — Bangladeshi Taka" },
  { value: "LKR", label: "LKR — Sri Lankan Rupee" },
  { value: "NPR", label: "NPR — Nepalese Rupee" },
  { value: "CNY", label: "CNY — Chinese Yuan" },
  { value: "KRW", label: "KRW — South Korean Won" },
  { value: "TWD", label: "TWD — Taiwan Dollar" },
  { value: "THB", label: "THB — Thai Baht" },
  { value: "IDR", label: "IDR — Indonesian Rupiah" },
  { value: "MYR", label: "MYR — Malaysian Ringgit" },
  { value: "PHP", label: "PHP — Philippine Peso" },
  { value: "VND", label: "VND — Vietnamese Dong" },
  { value: "BRL", label: "BRL — Brazilian Real" },
  { value: "MXN", label: "MXN — Mexican Peso" },
  { value: "ARS", label: "ARS — Argentine Peso" },
  { value: "CLP", label: "CLP — Chilean Peso" },
  { value: "COP", label: "COP — Colombian Peso" },
  { value: "PEN", label: "PEN — Peruvian Sol" },
  { value: "UYU", label: "UYU — Uruguayan Peso" },
  { value: "CRC", label: "CRC — Costa Rican Colón" },
  { value: "GTQ", label: "GTQ — Guatemalan Quetzal" },
  { value: "JMD", label: "JMD — Jamaican Dollar" },
  { value: "TTD", label: "TTD — Trinidad & Tobago Dollar" },
] as const;

export const CURRENCIES = CURRENCY_OPTIONS.map((c) => c.value) as unknown as readonly string[];

export const EXPERTISE_LEVELS = [
  { value: "junior", label: "Junior (1-3 years)" },
  { value: "mid", label: "Mid-level (3-6 years)" },
  { value: "senior", label: "Senior (6-10 years)" },
  { value: "expert", label: "Expert (10+ years)" },
] as const;

export const SKILLS = [
  "TouchDesigner",
  "Notch",
  "TiXL",
  "Unreal Engine",
  "Unity",
  "VVVV",
  "Processing",
  "openFrameworks",
  "Max/MSP",
  "Sound Design",
  "Generative Sound",
  "Spatial Sound",
  "Resolume",
  "MadMapper",
  "LED Mapping",
  "Projection Mapping",
  "LASER",
  "Lighting Design",
  "Motion Graphics",
  "3D Modeling",
  "Shader Programming",
  "Python",
  "System Design",
  "Hardware Integration",
  "Audio Reactive",
  "Generative Art",
  "Interactive Installation",
  "VJing",
  "Live Performance",
  "Sensors",
  "AR / VR",
  "AI / ML Integration",
] as const;

export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahrain",
  "Bangladesh",
  "Belarus",
  "Belgium",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Brazil",
  "Bulgaria",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Estonia",
  "Ethiopia",
  "Finland",
  "France",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Guatemala",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Latvia",
  "Lebanon",
  "Lithuania",
  "Luxembourg",
  "Malaysia",
  "Malta",
  "Mexico",
  "Moldova",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Pakistan",
  "Panama",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Tanzania",
  "Thailand",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Zimbabwe",
  "Other",
] as const;

export interface ProjectSubmission {
  id?: string;
  projectType: string;
  clientType: string;
  projectLength: string;
  clientCountry?: string;
  projectLocation: string;
  skills: string[];
  expertiseLevel: string;
  totalBudget?: number | null;
  yourBudget: number;
  daysOfWork?: number;
  currency: string;
  rateType: string;
  contractedAs?: string;
  rateRepresentativeness?: string;
  standardRate?: number;
  yourRole: string;
  yearCompleted: number;
  description?: string;
  createdAt?: string;
}
